app = 'blackkeys-prometheus'
primary_region = 'ord'

[build]
  image = 'prom/prometheus:v3.5.0'

[env]
  TZ = 'UTC'

[[mounts]]
  source = 'prometheus'
  destination = '/prometheus'
  initial_size = '1gb'

[[files]]
  guest_path = '/etc/prometheus/prometheus.yml'
  local_path = 'prometheus.yml'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
