global:
  scrape_interval: 25s

scrape_configs:
  - job_name: blackkeys-ws
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - blackkeys-ws.internal
        type: AAAA
        port: 9100
