{
 "title": "Blackkeys Overview",
 "description": "Blackkeys RAM, CPU, Disk and Net overview across all nodes.",
 "tags": [ "blackkeys" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=~\"blackkeys.*\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$job :: RAM % used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * (1 - (node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$job :: RAM % used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$job :: CPU % used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$job :: CPU % used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$job :: disk IO total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"$job\", device!~\"nbd.*\"}[$__rate_interval])) + sum(rate(node_disk_written_bytes_total{job=\"$job\", device!~\"nbd.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$job :: disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"$job\", device!~\"nbd.*\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"$job\", device!~\"nbd.*\"}[$__rate_interval]))",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "$job :: net IO total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"$job\", device=\"eth0\"}[$__rate_interval])) + sum(rate(node_network_transmit_bytes_total{job=\"$job\", device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$job :: net IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"$job\", device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"$job\", device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "tx"
    }
   ]
  }
 ]
}