apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: blackkeys-prometheus
    access: proxy
    url: http://blackkeys-prometheus.internal:9090
    isDefault: true
    jsonData:
      timeInterval: 25s
