app = 'blackkeys-assets'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  GRPC_ADDRESS = '::'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
